<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_ElementCompositionCustomized" Id="{95f3da27-97ba-45f4-bceb-4335121d4a01}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ElementCompositionCustomized
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;
]]></ST>
    </Implementation>
    <LineIds Name="FB_ElementCompositionCustomized">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>