<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_ConfigSubSystemEmulation" Id="{6634f33d-9a62-414a-af75-e09c5fffb480}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ConfigSubSystemEmulation : BOOL
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;
]]></ST>
    </Implementation>
    <LineIds Name="F_ConfigSubSystemEmulation">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>