<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_ConfigPositionEmulation_002" Id="{68c4d31b-ce0b-4a5c-8e38-919ceb2ce310}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ConfigPositionEmulation_002
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_ConfigPositionEmulation_002">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>