<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="F_GetTimeMsDiff" Id="{3c0fc3d0-5d53-4017-87ae-ca07e5bbf5d5}" SpecialFunc="None">
    <Declaration><![CDATA[// returns a timedifference (in milliseconds) from TimeMsTick to now
FUNCTION PUBLIC F_GetTimeMsDiff : TIME
(**************************************************************************************
 * 	Application		:	BoxControl Framework
 *	Revision		  :	$Revision: 461868 $
 *	Revision date	:	$Date: 1979-01-09 14:35:13 +0200 (Di., 09 Jan 1979) $
 *	Last changed by	:	$Author: b7lipim $
 *	URL				:	$URL: http://almscdc.swisslog.com/repo/SWPD/Development/BoxControlFramework/20_Release/branches/R1.x/01_Software/BCF/BCF/JumpStart/20_Product/10_BCF/10_Base/11_Com/12_DebugMsg/00_GVLs/DebugTextBlocks.TcGVL $
 *
 * ------------------------------------------------------------------------------------
 *	Copyright Swisslog [IP AG], Switzerland. All rights reserved.
 * 
 * ------------------------------------------------------------------------------------
 *	
 * 	Revision History: 
 *
 *  VERSION DATE         INITIALS     DESCRIPTION
 *  0.0     DD.MM.YYYY   (name)       (explain customized modifications)
 *
 **************************************************************************************)

(********************************************************************************************************************************)
VAR_INPUT
  TimeMsTick            : TIME                             := T#0S;
END_VAR

(********************************************************************************************************************************)
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
(********************************************************************************************************************************)
(** done ************************************************************************************************************************)
F_GetTimeMsDiff:= F_GetTimeMsTick() - TimeMsTick;]]></ST>
    </Implementation>
    <LineIds Name="F_GetTimeMsDiff">
      <LineId Id="3" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>