<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="F_StoppingDistance" Id="{3a15b82a-e3c4-464a-b737-5dabea841a40}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_StoppingDistance : UINT
(**************************************************************************************
 * 	Application		:	BoxControl Framework
 *	Revision		:	$Revision: 404529 $
 *	Revision date	:	$Date: 2018-04-23 08:21:38 +0200 (Mo., 23 Apr 2018) $
 *	Last changed by	:	$Author: b7bolm $
 *	URL				:	$URL: http://almscdc.swisslog.com/repo/SWPD/Development/BoxControlFramework/20_Release/trunk/01_Software/BCF/BCF/JumpStart/20_Product/10_App/12_E_Functions/10_Lib/10_Conv/10_Functions/F_StoppingDistance.TcPOU $
 *
 *	Purpose			:	Calculate stopping distance based on QB1 (distance until the TU is stopped in mm).
 *						
 *
 * ------------------------------------------------------------------------------------
 *	Copyright Swisslog [IP AG], Switzerland. All rights reserved.
 * 
 * ------------------------------------------------------------------------------------
 *	
 * 	Revision History: 
 *
 * 	VERSION			DATE			INITIALS			DESCRIPTION
 *	0.1				01.01.2001		swl					Example
 *
 **************************************************************************************)
VAR_INPUT
	CurrentSpeed : INT; // Current speed [mmm/s]
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Calculate distance besed on QB1 formula
F_StoppingDistance := LREAL_TO_UINT((((EXPT(CurrentSpeed,2) * MAX_LOADING * 50 / 2000) / (1.8 * 2))) / 1000);]]></ST>
    </Implementation>
    <LineIds Name="F_StoppingDistance">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>