<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="F_InRangeDint" Id="{33297c33-f2de-43f2-ba20-40365b99df5e}" SpecialFunc="None">
    <Declaration><![CDATA[///checks if the input n is within the range defined by low and high including them.
FUNCTION F_InRangeDint : BOOL
(**************************************************************************************
 *  Application     :   BoxControl Framework
 *  Revision date   :   $Date: 2021-04-09 08:29:02 +0200 (fre, 09 apr 2021) $
 *  Author          :   CDC
 * ------------------------------------------------------------------------------------
 *  © Swisslog AG
 *  Swisslog is not liable for any usage of this source code that is not agreed 
 *  on between Swisslog and the other party. The mandatory legal liability remains 
 *  unaffected.
 * ------------------------------------------------------------------------------------
 *  Revision History: 
 *
 *  VERSION DATE         INITIALS     DESCRIPTION
 *  0.0     DD.MM.YYYY   (name)       (explain customized modifications)
 *
 **************************************************************************************)
VAR_INPUT
	Low : DINT;
	N : DINT;
	High : DINT;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_InRangeDint := Low <= N AND N <= High;]]></ST>
    </Implementation>
    <LineIds Name="F_InRangeDint">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>